sudo: true
language: c
services:
- docker

# This is a hook to help us introduce "soft" errors on our process
matrix:
  allow_failures:
    - env: ALLOW_SOFT_FAILURE_HERE=true

# Install dependencies for all, once
#
install:
- sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev gnupg python-pip
- sudo apt install -y --only-upgrade docker-ce
- sudo pip install git-semver
- docker info

# Setup notification system
#
notifications:
  webhooks: https://app.fossa.io/hooks/travisci

# Define the stage sequence and conditionals
#
stages:
# Mandatory runs, we always want these executed
- name: Build process


# Define stage implementation details
#
jobs:
  include:
    # Ensure netdata code builds successfully
  - stage: Build process
   
    name: Docker container build process (alpine installation)
    script: packaging/docker/build.sh
    env: DEVEL="true"
    after_failure: post_message "TRAVIS_MESSAGE" "Docker build process failed"




